name: Suggestion
description: Help us improve with suggestions
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a talk to add to the list!
  - type: input
    id: suggestion
    attributes:
      label: Link to suggestion
      description: Please share a link to your suggestion
      placeholder: https://...
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the talk (in breif)
      description: How and why is your suggestion useful to this community?
      placeholder: I wish to see talk <xyz> here becuase...
    validations:
      required: true
