name: Publish

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          repository: HackSocNotts/hacksocnotts.github.io
          path: './hacksocnotts.github.io/'
          token: ${{ secrets.PERSONAL_TOKEN }}
      
      - uses: actions/checkout@v2
        with:
          path: './awesome-talks/'

      - run: ./awesome-talks/add-yaml.sh > ./hacksocnotts.github.io/content/awesome-talks.md
      - uses: EndBug/add-and-commit@v7
        with:
          message: 'Updated Events Page'
          add: 'content/awesome-talks.md  --force'
          cwd: './hacksocnotts.github.io/'
          push: false
      - name: Push changes
        run: |
          cd ./hacksocnotts.github.io/
          git push origin main
        env:
          username: ${{ secrets.USERNAME }}
